### ISSUE TITLE
Product setup missing mongodb database and collection setup files

### ISSUE THREAD

**Issue by sukhcs** [yeonholee50/AmpyFin#17]
No script to create the database and collection in mongodb.

**Comment by yeonholee50** [comment]
Yes, currently, the only workardoung is using the two separate functions, but I am writing a seperate file titled mongo_setup.py to help execute this. Thank you for posting

**Comment by yeonholee50** [comment]
Completed the set up script for mongo. Please take a look and if you approve, you can close the issue. If it doesn't work or isn't simplified, please lmk as well. Documented on README.md as well

**Comment by sukhcs** [comment]
Thanks. I have a related issue.
My script can't find **time_delta** in mongodb, under **trading_simulator** db
From ranking client:
   **time_delta = db.time_delta.find_one({})['time_delta']**

**Comment by yeonholee50** [comment]
Ahh it should initialize by itself which is what I'll make it do rn. Thank you. finding should only be done at the end for incrementing as well as during tradingto only use it for computation purposes for total_points

**Comment by yeonholee50** [comment]
I just implemented initializing time_delta as well for the setup script. Please take a look and if you approve, you can close the issue. If it doesn't work or isn't simplified, please lmk as well. Thanks for the feedback

**Comment by sukhcs** [comment]
Thank you,

what is under trades db?

Can you please share the document structure for **rank** collection and all collections under **trades**?

**Comment by yeonholee50** [comment]
rank will initialize itself at the end of the trading iteration. - first time market is closing. collections under trades looks like this 
![image](https://github.com/user-attachments/assets/25cdc6a5-66ab-44d2-9776-531ed83d34d3)

**Comment by sukhcs** [comment]
The trades collections were created automatically by the trading script.  The rank collection updated at the end of the day. I am able to get the product up and running. Thank you for your help. 

@yeonholee50
