### ISSUE TITLE
Learned Strategies

### ISSUE THREAD

**Issue by moyuanchen** [yeonholee50/AmpyFin#19]
Hi Yeonholle,

Cool repo! I saw your post on Reddit and wanted to reach out. I am also building a ML trading bot. Something in line of this: 
[Volitility.pdf](https://github.com/user-attachments/files/18045277/Volitility.pdf)

Have you considered letting the neural network to learn trading strategies on its own instead of providing it with legacy strategies? I feel like that would be the best way to leverage the power of neural networks.

Let me know if you would like to chat!

Best,

Mike

**Comment by yeonholee50** [comment]
Hello Mike. Thank you for the comment. Do you have discord by any chance. You can add me on yeon_lee50. After you add me, you can close this issue and we can discuss there.
