### ISSUE TITLE
Occasinal Crashing Every 2 Weeks

### ISSUE THREAD

**Issue by yeonholee50** [yeonholee50/AmpyFin#2]
There is a current issue with the training model where it crashes at most once every 2 weeks - I've been keeping an eye on it and restarting manually when this happens. If someone can create a script or some sort of process where the ranking and trading clients restart after crash, this would be highly appreciated. Please reach out if you have any questions.

**Comment by yeonholee50** [comment]
Update: I figured out it's a HTTPS Connection Error so I will take a further look at it in the coming days to either resolve it or find a workaround

**Comment by maks1m** [comment]
Do you have a stacktrace from the error?

**Comment by yeonholee50** [comment]
> Do you have a stacktrace from the error?
I was able to fix this when implementing threading. Essentially I was calling too many mongo instances in rank which was flooding connections in mongodb. It should be fixed now.
