### ISSUE TITLE
Momentum strategy railing issue

### ISSUE THREAD

**Issue by Morritse** [yeonholee50/AmpyFin#22]
As written, the strategy essentially collapses all scenarios where the short-term moving average (short_ma) is less than the long-term moving average (long_ma) into a single extreme sentiment outcome. Here’s why this happens:

Derivation of Raw Sentiment:

```
ratio = short_ma / long_ma
raw_sentiment = (ratio - 1) * 1000
```

When short_ma < long_ma, ratio < 1. This makes (ratio - 1) negative, and so raw_sentiment will be a negative number.

Forcing the Sentiment to be at Least 1:
In the current logic, if `short_ma > long_ma,` sentiment is capped at min(100, int(raw_sentiment))—meaning it can vary from 0 to 100. However, if `short_ma <= long_ma`, the sentiment is set by:

`sentiment = max(1, int(raw_sentiment))`
Since raw_sentiment is negative in this scenario, `int(raw_sentiment)` will be less than or equal to 0. Applying `max(1, negative_number) ` always results in 1. Effectively, you lose all granularity on the downside—no matter how close or far the short MA is below the long MA, the sentiment will always be 1.

Implications for Signals:
Because sentiment will always return as 1 in the short < long scenario, the logic that checks for sell signals will always find sentiment ≤ 20 and thus always produce a "strong sell" signal if you hold any quantity. This prevents the strategy from ever issuing a more moderate "sell" signal or even a subtle "hold" as long as short_ma < long_ma.

How to Improve Granularity:
If you want to introduce more gradation for the bearish scenario (short < long), you could consider allowing sentiment to range down to negative values or simply rescale the negative raw_sentiment values into a lower range. For example, you might do something like this:

Keep the sentiment range consistent on both sides. If (ratio - 1) * 1000 yields a negative number, you could transform that negative number into, say, a range of 0 to 40 (to reflect milder sell signals) rather than forcing it to 1. 

Another more straightforward strategy would be to predefine ranges to signals directly.
I realize this breaks with the continuous sentiment calculation but an example would be simply to bucket ratios into signals. fundamentally we're bucketing sentiments into decisions anyways, so you don't lose and resolution. 

Using predefined ratio thresholds is a straightforward and transparent approach. It may be more intuitive than attempting to continuously map the ratio to a sentiment scale. By selecting clear-cut bands, you ensure that small deviations around 1.0 lead to subtle signals (hold or light buy/sell), while larger deviations trigger stronger signals.

.
Below is one reasonable set of thresholds, symmetric around 1.0:

Strong Sell: Ratio ≤ 0.95
(Short MA is at least 5% below the Long MA, indicating strong downward momentum)

Light Sell: 0.95 < Ratio < 0.99
(Short MA is 1%-5% below the Long MA, a moderate bearish signal but not too severe)

Hold: 0.99 ≤ Ratio ≤ 1.01
(Short MA is within ±1% of Long MA, suggesting a relatively neutral market with no strong directional bias)

Light Buy: 1.01 < Ratio < 1.05
(Short MA is 1%-5% above the Long MA, indicating mild upward momentum)

Strong Buy: Ratio ≥ 1.05
(Short MA is at least 5% above the Long MA, signaling strong bullish momentum)

You can tweak the exact percentage thresholds (e.g., 1%, 5%, etc.) depending on how sensitive you want the system to be, or convert these from 0-100 sentiment scores if you want to be consistent.

**Comment by yeonholee50** [comment]
I have changed the strategies so that it will now be using ta-lib which is a better library for indicators. A lot of strategies I implemented were from textbooks, academic journals etc. so although I tried to make each of them work as well as I could, they really weren't at closer inspection so I apologize. Also the way I implemented the functions in ta-lib are still static but I plan to make it dynamic in terms of how parameters will work - like the period, other params etc. Please let me know if you still have any questions.
