### ISSUE TITLE
Create a Well Documented README.md for set up process

### ISSUE THREAD

**Issue by yeonholee50** [yeonholee50/AmpyFin#9]
A lot have been complaining that the set up process is complex, especially involving MongoDB, so I'm making this an issue to get it resolved as soon as possible so people can start using it

**Comment by NitinDatta8** [comment]
I had similar issues with setup of the collections rank. 
Running the trading_client.py during market hours for the FIRST TIME leads to an error as it cannot find the ranks collection in trading_simulator database. 

Maybe we can fix that by assigning inital ranks in setup.py

**Comment by yeonholee50** [comment]
completed
